/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/environment/glaciers.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Glacier2(props) {
  const { nodes, materials } = useGLTF('./models/environment/glaciers.glb')
  return (
    <group {...props} dispose={null}>
      {/* <mesh  geometry={nodes.Landscape.geometry} material={materials['Material.002']} position={[0,0,0]} /> */}
      {/* <mesh  geometry={nodes.Landscape001.geometry} material={materials['Material.001']} position={[0,0,0]} /> */}
      <mesh  geometry={nodes.Landscape002.geometry} material={materials.Material} position={[0,0,0]} />
    </group>
  )
}

useGLTF.preload('./models/environment//glaciers.glb')
