/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ocean_4.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ocean(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./models/environment/ocean_4.glb')
  const { actions } = useAnimations(animations, group)
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="large002" geometry={nodes.large002.geometry} material={materials['Material.006']} morphTargetDictionary={nodes.large002.morphTargetDictionary} morphTargetInfluences={nodes.large002.morphTargetInfluences} scale={[1, 1.058, 1]} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/environment/ocean_4.glb')
