/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ship/SHIP_PROMETEO_2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./models/ship/SHIP_PROMETEO_2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ship002.geometry} material={materials['Material.005']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship003.geometry} material={materials['Material.004']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship004.geometry} material={materials['PROMETEO FLAG']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship005.geometry} material={materials['Material.001']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship006.geometry} material={materials['Material.003']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship007.geometry} material={materials.metall} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship008.geometry} material={materials['rope remake']} position={[0, 0, -66.352]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/ship/SHIP_PROMETEO_2.glb')
