/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ship/models/ship/SHIP_PROMETEO.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ShipFinal(props) {
  const { nodes, materials } = useGLTF('./models/ship/SHIP_PROMETEO.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ship049.geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship533.geometry} material={materials['Material.004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship548.geometry} material={materials['PROMETEO FLAG']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship534.geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship001.geometry} material={materials['Material.003']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship873.geometry} material={materials.metall} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.ship930.geometry} material={materials['rope remake']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/ship/SHIP_PROMETEO.glb')
