export default [
    {
        "id": 49,
        "name": "Water Bottle Rocket",
        "speaker": "",
        "designation": "",
        "image": "images/Bottle_Rockets.jpeg",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 4,
        "prize": "12K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "",
        "date": "2024-01-21",
        "time": "15:00:00",
        "end_date": "2024-01-21",
        "end_time": "17:00:00",
        "venue": "I2 Grounds",
        "registration_open": "1",
        "type": "informal",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 48,
        "name": "Egg Drop",
        "speaker": "",
        "designation": "",
        "image": "images/egg_drop.jpg",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 2,
        "prize": "10K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "",
        "date": "2024-01-20",
        "time": "16:00:00",
        "end_date": "2024-01-20",
        "end_time": "18:00:00",
        "venue": "Informal Grounds",
        "registration_open": "1",
        "type": "informal",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 47,
        "name": "Bridge Making",
        "speaker": "",
        "designation": "",
        "image": "images/BRIDGE_MAKING.jpg",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 4,
        "prize": "5K INR",
        "description": "Join us for an exciting Bridge Making Event where creativity and engineering skills collide! Participants will have the opportunity to design and construct their own miniature bridges using a variety of materials. This hands-on experience will not only challenge your problem-solving abilities but also foster teamwork and innovation. Come bridge the gap between imagination and reality in this fun-filled event where bridges aren't just structures, but gateways to new possibilities!",
        "poster_description": "",
        "host": "",
        "external_link": "https://docs.google.com/forms/d/e/1FAIpQLSejsRBcow6li89H7ZzcLt2QYq1tZKN2_6CvcWDbCvDmBwbaYg/viewform?usp=sf_link",
        "date": "2024-01-19",
        "time": "16:00:00",
        "end_date": "2024-01-01",
        "end_time": "19:00:00",
        "venue": "LHC  305",
        "registration_open": "1",
        "type": "informal",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 46,
        "name": "Pick and Place",
        "speaker": "",
        "designation": "",
        "image": "images/pnp.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 20K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/pick-and-place-prometeo24-indian-institute-of-technology-iit-jodhpur-862656",
        "date": "2024-01-19",
        "time": "10:55:40",
        "end_date": "2024-01-21",
        "end_time": "10:55:46",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 45,
        "name": "WireWizard-Arduino",
        "speaker": "",
        "designation": "",
        "image": "images/arduino-challenge-in-technology-164231062.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 20K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/wirewizard-arduino-challenge-prometeo24-indian-institute-of-technology-iit-jodhpur-851055?utm_campaign=site-emails&utm_medium=d2c-automated&utm_source=opportunity-approved",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-21",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 44,
        "name": "Web3",
        "speaker": "",
        "designation": "",
        "image": "images/web.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "5K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/workshops-webinars/web3-workshop-prometeo24-indian-institute-of-technology-iit-jodhpur-855940",
        "date": "2024-01-13",
        "time": "12:00:00",
        "end_date": "2024-01-13",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "workshop",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 43,
        "name": "Robot Modelling and Control",
        "speaker": "",
        "designation": "",
        "image": "images/robo_modelling.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "20K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/workshops-webinars/robot-modeling-and-control-using-matlab-workshop-prometeo24-indian-institute-of-technology-iit-jodhpu-855942",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "18:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "workshop",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 41,
        "name": "Warehouse Management ROS",
        "speaker": "",
        "designation": "",
        "image": "images/warehouse.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "5K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/p/warehouse-management-with-ros-prometeo24-indian-institute-of-technology-iit-jodhpur-855941",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-20",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "workshop",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 40,
        "name": "Prompt Engineering",
        "speaker": "",
        "designation": "",
        "image": "images/peng.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "3K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/workshops-webinars/prompt-engineering-workshop-prometeo24-indian-institute-of-technology-iit-jodhpur-855953",
        "date": "2024-01-20",
        "time": "12:00:00",
        "end_date": "2024-01-21",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "workshop",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 39,
        "name": "ML Hackathon",
        "speaker": "",
        "designation": "",
        "image": "images/ml_hackathon.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "25K INR",
        "description": "",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/ml-hackathon-prometeo24-indian-institute-of-technology-iit-jodhpur-852160",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-21",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 38,
        "name": "Trade Tussle",
        "speaker": "",
        "designation": "",
        "image": "images/trade.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 3K INR",
        "description": "Welcome to \"Trade-Tussle\", an exhilarating virtual trading challenge hosted as part of our fest, Prometeo E-conclave. This unique event is designed to bring together participants from various colleges, offering them a hands-on experience in the dynamic world of stock market trading. Trade-Tussle is not just a competition; it's an opportunity for participants to refine their trading strategies, learn from market dynamics, and emerge as skilled investors. Get ready for a week of financial exploration and strategic maneuvering in Trade-Tussle.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/trade-tussle-prometeo24-indian-institute-of-technology-iit-jodhpur-829750",
        "date": "2024-01-01",
        "time": "10:00:00",
        "end_date": "2024-01-12",
        "end_time": "20:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 37,
        "name": "Cryptic Hunt",
        "speaker": "",
        "designation": "",
        "image": "images/cryptic_hunt.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 4,
        "prize": "Prize 5K INR",
        "description": "Cryptic Hunt is all about finding clues, deciphering them, and reaching the final answer by connecting the dots. Participants will need to use their skills in programming, cryptography, forensics, and critical thinking to beat the competition.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/cryptic-hunt-prometeo24-indian-institute-of-technology-iit-jodhpur-828585?lb=j5wZ3hW&utm_medium=Share&utm_source=WhatsApp",
        "date": "2024-01-05",
        "time": "15:00:00",
        "end_date": "2024-01-06",
        "end_time": "15:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 36,
        "name": "UXpert",
        "speaker": "",
        "designation": "",
        "image": "images/ui_ux.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 12K INR",
        "description": "The UI/UX Designing Hackathon is an excellent opportunity for students to showcase their creative and innovative skills.",
        "poster_description": "",
        "host": "",
        "external_link": "",
        "date": "2024-01-04",
        "time": "00:00:00",
        "end_date": "2024-01-07",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 35,
        "name": "Quantopia",
        "speaker": "",
        "designation": "",
        "image": "images/quant.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 5K INR",
        "description": "Listen up, math whizzes! Are you the ultimate puzzle-solving sensation? Then, get ready to\r\nflex your numbers muscle in the contest you've been waiting for! This event will put your probability skills, mathematical wit, and logical reasoning to the test. So, come armed\r\nwith your passion for numbers and sharp thinking skills.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/quiz/quantopia-prometeo24-indian-institute-of-technology-iit-jodhpur-828592?lb=jHkkhyxt&utm_medium=Share&utm_source=WhatsApp",
        "date": "2023-12-19",
        "time": "17:00:00",
        "end_date": "2023-12-19",
        "end_time": "17:45:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 34,
        "name": "HackGen",
        "speaker": "",
        "designation": "",
        "image": "images/hackgen.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 5K INR",
        "description": "Pioneering the national-level Prompt Engineering and Generative AI competition - HackGen! Register and test your combination of prompt engineering skills to generate AI images like never before!",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/hackgen-24-prometeo24-indian-institute-of-technology-iit-jodhpur-833826",
        "date": "2023-12-23",
        "time": "11:00:00",
        "end_date": "2023-12-26",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 33,
        "name": "ML Codefest",
        "speaker": "",
        "designation": "",
        "image": "images/ml_.jpg",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 4,
        "prize": "Prize 5K INR",
        "description": "What happens when you hear the words “Data Science” and “Machine Learning”? Isn’t it futuristic tech that comes to your mind? Indeed, they will have a huge role in our lives in upcoming times. We present to you a platform to test your enthusiasm. Data science and Machine Learning enthusiasts prime yourselves for a ML Hackathon! It is a week-long thrilling hackathon where you will be asked to solve tasks of varying complexities designed by experts and the participants coming up with the most innovative and efficient solutions will be rewarded. Register and give your machine learning skills an unprecedented and unique challenge.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/ml-codefest-prometeo24-indian-institute-of-technology-iit-jodhpur-847614",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 32,
        "name": "Code Golf",
        "speaker": "",
        "designation": "",
        "image": "images/code_golf.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 7K INR",
        "description": "Code golf is a unique and exciting form of competitive programming where participants aim to solve a particular problem using the shortest possible source code. It's a test of both programming skill and creativity, pushing participants to craft concise, efficient, and often unconventional solutions.",
        "poster_description": "",
        "host": "",
        "external_link": "https://www.hackerrank.com/code-golf-6",
        "date": "2024-01-04",
        "time": "18:30:00",
        "end_date": "2024-01-01",
        "end_time": "20:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 31,
        "name": "CADastra",
        "speaker": "",
        "designation": "",
        "image": "images/CAD_qLbAnfn.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 5K INR",
        "description": "It will be an on-spot designing round where participants will be given a problem statement at the time of the event and will have to submit their design within the specified time limit.  \r\nModels can be prepared in any CAD software (Fusion 360 /CATIA/ ProE/Autocad/ Solidworks/ Solidedge).",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/p/cadastra-prometeo24-indian-institute-of-technology-iit-jodhpur-828613?lb=OSKORI6D&utm_medium=Share&utm_source=Mail",
        "date": "2023-12-19",
        "time": "12:00:00",
        "end_date": "2023-12-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 29,
        "name": "Revive Quest",
        "speaker": "",
        "designation": "",
        "image": "images/revive_quest.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 4,
        "max_team_size": 5,
        "prize": "Prize 20K INR",
        "description": "Revive Quest is a business innovation challenge where teams will be tasked with resurrecting a previously failed business/company and navigating it through unique market disruptions. Participants will analyse and propose alternative business models to steer the company away from its downfall, using their advantage of hindsight and guide it through changed market conditions, showcasing their techno-entrepreneurial acumen.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/revive-quest-breathing-new-life-into-business-legacies-prometeo24-indian-institute-of-technology-iit-jodhpu-845607?lb=07DAPlDJ&utm_medium=Share&utm_source=shortUrl",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 28,
        "name": "Poster Presentation",
        "speaker": "",
        "designation": "",
        "image": "images/poster.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "individual",
        "min_team_size": 1,
        "max_team_size": 1,
        "prize": "Prize 60K INR",
        "description": "Creating a poster presentation is an artistic endeavor that condenses days of effort into a concise 2-minute visual display. It is  a unique event in which the audience is enriched with the creativity and intellect of the research without much of a description.\r\nGear up and participate in this pan India Poster Presentation competition and showcase your work as well as witness the work of budding researchers.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/poster-presentation-prometeo-24-indian-institute-of-technology-iit-jodhpur-846977",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 27,
        "name": "Line Follower",
        "speaker": "",
        "designation": "",
        "image": "images/line_follower.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 6,
        "prize": "Prize 30K INR",
        "description": "Line Follower is a Prometeo'24 event where teams showcase their autonomously operating, self-designed robots. These robots are tasked with navigating from the starting position to the final position, choosing the shortest path, and minimizing the time taken while avoiding dead ends.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/line-follower-prometeo24-indian-institute-of-technology-iit-jodhpur-846946",
        "date": "2024-01-19",
        "time": "10:00:00",
        "end_date": "2024-01-20",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 26,
        "name": "Capture the Flag: CTF",
        "speaker": "",
        "designation": "",
        "image": "images/cyber_sec.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 20K INR",
        "description": "Capture the Flag”, or CTF for short, involves a set of challenging problems related to cybersecurity, cryptography, forensics, memory corruption, and other web technologies, which the player needs to solve to obtain a “flag” that can be exchanged for points.\r\nA “flag” is a string consisting of alphabet letters, digits, and symbols. The teams with more points move up the leaderboard.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/capture-the-flag-ctf-prometeo24-indian-institute-of-technology-iit-jodhpur-847525",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 25,
        "name": "DevQuest",
        "speaker": "",
        "designation": "",
        "image": "images/devquest.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 5,
        "prize": "Prize 40K INR",
        "description": "Participants need to build a web/mobile application(website or app) that aligns with the problem statement and that too within the stipulated time constraint.\r\nParticipants are expected to ideate, code, test, optimize and deploy an application according to the problem statements and should focus on the user interface and user experience for the application.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/devquest-prometeo-24-indian-institute-of-technology-iit-jodhpur-844083",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 24,
        "name": "Tech Trivia Quiz",
        "speaker": "",
        "designation": "",
        "image": "images/tech_quiz.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 20K INR",
        "description": "Prometeo brings you a great opportunity to put your technical knowledge to the test. This event is designed to push the boundaries of your expertise with a wide array of questions spanning various tech disciplines. Show off your technological prowess and win the title of the most tech-savvy quizzer in this exciting technical quiz competition.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/quiz/tech-trivia-quiz-prometeo24-indian-institute-of-technology-iit-jodhpur-844134",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 22,
        "name": "Robo-Soccer",
        "speaker": "",
        "designation": "",
        "image": "images/robosoccer.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 5,
        "prize": "Prize 30K INR",
        "description": "Robosoccer is an event in Prometeo'24 where teams come with their own remote control or wired robot with the ability to compete against other robots in a tournament.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/robosoccer-prometeo-24-indian-institute-of-technology-iit-jodhpur-842463",
        "date": "2024-01-19",
        "time": "16:00:00",
        "end_date": "2024-01-20",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 21,
        "name": "Drone Racing",
        "speaker": "",
        "designation": "",
        "image": "images/droneracing.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 10,
        "prize": "Prize 100K INR",
        "description": "Drone racing league is an event in Prometeo'24 where teams come with their own FPV Drone with the ability to compete against other Drones in a tournament.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/p/drone-racing-league-indian-institute-of-technology-iit-jodhpur-850862",
        "date": "2024-01-19",
        "time": "15:00:00",
        "end_date": "2024-01-21",
        "end_time": "23:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 20,
        "name": "Algo Trading",
        "speaker": "",
        "designation": "",
        "image": "images/algo_trading.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 25K INR",
        "description": "The primary goal of this research undertaking is to conduct a backtesting and assessment of a quantitative trading strategy. Participants must develop or explore existing quant and statistical tools/methods to automatically identify trading signals for testing the strategy in the options market.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/quantalytics-prometeo-24-indian-institute-of-technology-iit-jodhpur-850069",
        "date": "2024-01-14",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 19,
        "name": "Guesstimate",
        "speaker": "",
        "designation": "",
        "image": "images/guesstimate_sfhkVRZ.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 2,
        "prize": "Prize 10K INR",
        "description": "Guesstimate is a competition hosted by Prometeo, a technical and entrepreneurial fest. It is an event in which participants will be challenged to make educated guesses or estimates about various scenarios, statistics, or figures.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/quiz/guesstimate-master-the-art-of-precision-in-every-guess-prometeo-24-indian-institute-of-technology-iit-jodhpur-847265",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-20",
        "end_time": "15:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 18,
        "name": "RC Nitro Racing",
        "speaker": "",
        "designation": "",
        "image": "images/rc_car.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 4,
        "prize": "Prize 50K INR",
        "description": "Gear up for an electrifying fusion of technology and speed at Prometeo's RC Nitro Racing! This high-octane event brings together the best in remote control off-road racing, where miniature beasts of speed tackle rugged terrains.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/rc-nitro-racing-prometeo-24-indian-institute-of-technology-iit-jodhpur-850117",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 17,
        "name": "RoboWars",
        "speaker": "",
        "designation": "",
        "image": "images/robowars.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 20,
        "prize": "Prize 125K INR",
        "description": "Robowars is the flagship event of Prometeo'24 where teams come with their self-designed & remote-controlled robot capable to fight in a tournament agains other robots.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/robowars-prometeo24-indian-institute-of-technology-iit-jodhpur-840261",
        "date": "2024-01-19",
        "time": "15:00:00",
        "end_date": "2024-01-21",
        "end_time": "23:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 16,
        "name": "Code Relay",
        "speaker": "",
        "designation": "",
        "image": "images/programming.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 3,
        "max_team_size": 3,
        "prize": "Prize 20K INR",
        "description": "Reverse coding to be done where you are given the expected output for certain inputs, and your task is to deduce the underlying algorithm or logic that produces that output .\r\nThe following round consists of simple algorithmic problems based on DSA.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/hackathons/code-relay-prometeo24-indian-institute-of-technology-iit-jodhpur-842538",
        "date": "2024-01-19",
        "time": "17:36:00",
        "end_date": "2024-01-19",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 15,
        "name": "Game-Jam",
        "speaker": "",
        "designation": "",
        "image": "images/game_jam.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 15,
        "prize": "Prize 100K INR",
        "description": "Prometeo 2024 marks the fourth installment of IIT Jodhpur's National Technical and Entrepreneurial Festival. Deriving its name and vision from the Greek fore-thinker “Prometheus”, who imparted the knowledge of technology and civilization to humanity, Prometeo aspires to elevate innovation, channeling creative ideas towards an enhanced impact at the forefront of progress. It features a dynamic blend of talks, workshops, and competitions that immerse participants in the vast world of emerging technology. In an age marked by formidable challenges confronting humanity, Prometeo aims to foster collaboration and nurture a community of innovators contributing to the world’s technological prowess to overcome, for its ultimate goal is to elevate, transform, and conquer.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/game-jam-prometeo24-indian-institute-of-technology-iit-jodhpur-849391",
        "date": "2024-01-19",
        "time": "00:00:00",
        "end_date": "2024-01-21",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "technical",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 14,
        "name": "Business Darbar",
        "speaker": "",
        "designation": "",
        "image": "images/bdarbar_dbRTVuD.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 4,
        "prize": "Prize 125K INR",
        "description": "Business Darbar, Prometeo's flagship Entrepreneurial Event, transcends traditional pitching forums by providing a dynamic platform where aspiring entrepreneurs present their ventures to a distinguished panel of investors. This exclusive opportunity goes beyond a mere presentation, offering participants constructive feedback, invaluable mentorship, and the prospect of securing crucial funding. More than an event, Business Darbar is a nexus where entrepreneurial visions converge with strategic guidance, propelling ventures to new heights. Step into the zenith of entrepreneurial brilliance, where innovation meets opportunity, fostering a vibrant ecosystem for the next wave of successful entrepreneurs.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/business-darbar-prometeo24-indian-institute-of-technology-iit-jodhpur-846100",
        "date": "2023-12-21",
        "time": "00:00:00",
        "end_date": "2024-01-19",
        "end_time": "00:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "1",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 13,
        "name": "The BoardRoom",
        "speaker": "",
        "designation": "",
        "image": "images/boardroom_oay8u9w.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 5,
        "prize": "Prize 20K INR",
        "description": "Be a responsible boardroom member of the Company and ideate and discuss the problem given in the boardroom meeting and present it in the press release.\r\nThe vision of this event is to give you the opportunity to get an idea of how a boardroom meeting undergoes.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/the-boardroom-prometeo24-indian-institute-of-technology-iit-jodhpur-846586",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 12,
        "name": "BPlan",
        "speaker": "",
        "designation": "",
        "image": "images/bplan.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 35K INR",
        "description": "B-Plan is a 36-hour business planning challenge where participating teams must create a complete strategy for a product or service defining a company's primary business operations and how it intends to reach its objectives for the provided problem statement from scratch.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/b-plan-business-planning-challenge-prometeo24-indian-institute-of-technology-iit-jodhpur-847166",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 11,
        "name": "BizQuiz",
        "speaker": "",
        "designation": "",
        "image": "images/bizquiz.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 3,
        "prize": "Prize 5K INR",
        "description": "Embark on a riveting journey of knowledge and strategy with our Business Quiz a dynamic fusion of intellect and acumen. Unleash your business prowess, tackle challenging scenarios, and emerge as the mastermind in this thrilling test of corporate wit.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/quiz/bizquiz-prometeo24-indian-institute-of-technology-iit-jodhpur-845603",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 10,
        "name": "ProdPulse",
        "speaker": "",
        "designation": "",
        "image": "images/prodpulse_z3ptOkW.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 3,
        "prize": "Prize 36K INR",
        "description": "ProdPulse is a product management case competition hosted by the Prometeo-Technical and Entrepreneurial Fest with the collaboration of The Product Folks. This competition is designed to bring together the brightest minds in product management, offering a platform for aspiring and seasoned product managers to showcase their skills, creativity, and strategic thinking.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/tpf-x-iit-jodhpur-prodpulse-prometeo24-indian-institute-of-technology-iit-jodhpur-847847",
        "date": "2024-01-03",
        "time": "12:00:00",
        "end_date": "2024-01-20",
        "end_time": "18:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 9,
        "name": "Ideathon",
        "speaker": "",
        "designation": "",
        "image": "images/ideathon_AGKQO70.png",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 1,
        "max_team_size": 5,
        "prize": "Prize 35K INR",
        "description": "Ideathon is a 24-hour brainstorming challenge in which participants should develop the best potential solution to a real case problem statement about a business plan or product. It entails problem-solving analysis, design thinking, and presenting ideas most effectively.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/competitions/ideathon-prometeo24-indian-institute-of-technology-iit-jodhpur-848006",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "entrepreneurial",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    },
    {
        "id": 8,
        "name": "Case Craft",
        "speaker": "",
        "designation": "",
        "image": "images/case_study.webp",
        "rulebook": "",
        "problem_statement": "",
        "sponsor_image1": "",
        "sponsor_website": "",
        "participation_type": "team",
        "min_team_size": 2,
        "max_team_size": 3,
        "prize": "Prize 5K INR",
        "description": "This competition demands participants to thoroughly analyze a given case problem within the realm of technology. This involves delving into market scenarios, organizational challenges, or specific issues, requiring a comprehensive approach to resolve complexities or rationalize the presented case. The real-life problems provided will expand participants' understanding of diverse market landscapes and operational intricacies within the tech domain.",
        "poster_description": "",
        "host": "",
        "external_link": "https://unstop.com/p/case-craft-case-study-competition-prometeo24-indian-institute-of-technology-iit-jodhpur-829735",
        "date": "2024-01-19",
        "time": "12:00:00",
        "end_date": "2024-01-19",
        "end_time": "12:00:00",
        "venue": "",
        "registration_open": "1",
        "type": "pre_events",
        "event_started": "0",
        "meet_link": "",
        "youtube_link": "",
        "webx_link": "",
        "featured": "0",
        "rank": 1,
        "hidden": "0",
        "presentation_template": "",
        "sample_poster": "",
        "submissions_started": "0",
        "submission_link": "",
        "material_name": "",
        "material": ""
    }
]