/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/text./models/text/event.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EventText(props) {
  const { nodes, materials } = useGLTF('./models/text/event.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve003.geometry} material={materials['Material.001']} position={[0, 0, 0]} />
    </group>
  )
}

useGLTF.preload('./models/text/event.glb')
