/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/text./models/text/welcome.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function WelcomeText(props) {
  const { nodes, materials } = useGLTF('./models/text/welcome.glb')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Curve.geometry} position={[0, 0, 0]} >
        <meshStandardMaterial color={'#1F4E5F'} envMapIntensity={3} />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/text/welcome.glb')
